name: C encapsulation commit gate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: ./scripts/install_build_dependencies.sh

    - name: Run unit tests
      run: make test

    - name: Build lenient encapsulation demo
      run: make out/lenient

    - name: Run lenient encapsulation demo
      run: ./out/lenient

