name: C encapsulation commit gate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: ./scripts/install_build_dependencies.sh

    - id: call-approval-test
      uses: ./.github/actions/approval-test
